[stack_nodes]
; This IP is a placeholder. It will automatically be substituted by Terraform outputs during a real CI/CD pipeline.
10.0.1.50 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/sovern-prod.pem
